<?php

/**
 * Main application entry point.
 * 
 * - Initializes the application environment and handles error reporting for development mode using Whoops.
 * - Instantiates the Request object with global variables ($_GET, $_POST, $_FILES, $_SERVER).
 * - Creates the Router object and runs the application, which determines the appropriate controller and action to execute.
 * - Outputs the response generated by the Router.
 *
 * Constants:
 * - APP_ENV: Defines the application environment ('dev' for development).
 */


declare(strict_types=1);

 
require_once __DIR__ . '/../vendor/autoload.php';
use App\Service\Request;
use App\Service\Router;

const APP_ENV  = 'dev';

if (APP_ENV === 'dev') {
    $whoops = new \Whoops\Run();
    $whoops->pushHandler(new \Whoops\Handler\PrettyPageHandler());
    $whoops->register();
}

$request = new Request($_GET, $_POST, $_FILES, $_SERVER);
$router = new Router($request);
$response = $router->run();
echo $response;
